/*
WRITE AN ALGORITHM AND PROGRAM FOR FOLLOWING USING RECURSION:
a. FIND THE FACTORIAL FOR GIVEN NUMBER ‘N’.
b. FIND THE FIBONACCI NUMBER FOR GIVEN TERM ‘N’.
c. SOLVE ABOVE QUESTIONS (a And b) USING TAIL RECURSION.
d. SOLVE TOWER OF HANOI PROBLEM FOR ‘N’ DISCS.
*/
